#
# Copyright The OpenZipkin Authors
# SPDX-License-Identifier: Apache-2.0
#

# MongoDB test image for Zipkin integration tests
FROM mongo:7.0

LABEL org.opencontainers.image.description="MongoDB for Zipkin integration tests"

EXPOSE 27017
